version: '3'
services:
  fsd-app:
    image: fsd-app:1.0
    build: .
    ports:
      - 3000
    environment:
      - 'REDIS_HOST=redis'
      - 'MONGOLAB_URI=mongodb://mongo:27017/myappdb'
    labels: 
      - "traefik.frontend.rule=Host:localhost"
    depends_on:
     - mongo
    links:
      - mongo
      - redis
  mongo:
    container_name: mongo
    image: mongo:4.0.4
    ports:
      - "27017:27017"
  redis:
    image: redis
    ports:
      - "6379:6379"
  reverse-proxy:
    image: traefik
    command: --api --docker
    ports:
      - "80:80"     # The HTTP port
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
 
    